modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "mondoteleport"
version = "${version}"
displayName = "MondoTeleport"
authors = "Kotori0629"
description = '''

'''
#logoFile = ""

[[dependencies.mondoteleport]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mondoteleport]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mondoteleport]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
