modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "mondoteleport"
version = "${version}"
displayName = "MondoTeleport"
authors = "Kotori0629"
description = '''

'''
#logoFile = ""

[[dependencies.mondoteleport]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mondoteleport]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mondoteleport]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mondoteleport.mixins.json"